In [114]:
import model_cls as model
from alg_joblisting import InitSchedule
from alg_tabu import JointScheduleProb, TabuSearch

import numpy as np
import pandas as pd
import time
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
plt.style.use('seaborn')

In [120]:
full_path = 'scenario/due_time_H/due_time_H_2.txt'  # benchmark/benchmark_1

data = model.Data()
data.read_data(in_path=full_path)

# init job schedule
sched_init = InitSchedule(data)
sched_init.due_weight_sort()
sched = JointScheduleProb(sched_init)

In [121]:
# tabu due_time_H_2
sched.scheduled_job_id = np.array([16,  3, 12, 13,  1, 20, 19, 
                                   14,  7,  5,  9,  2, 15,  8, 
                                   18, 11,  4, 10, 17,  6])
print(sched.scheduled_job_id)
# tabu
sched.scheduled_maint_pos = np.array([5, 0, 0, 0, 0])

print(sched.scheduled_maint_pos, sched.obj_value())

[16  3 12 13  1 20 19 14  7  5  9  2 15  8 18 11  4 10 17  6]
[5 0 0 0 0] 0.0


In [116]:
# tabu 1
sched.scheduled_job_id = np.array([4, 6, 14,  8, 12,  3, 20,
                                   9,  1, 16,  5, 18, 10,  2,
                                   7, 17, 13, 19, 11, 15])
print(sched.scheduled_job_id)
# tabu
sched.scheduled_maint_pos = np.array([0, 0, 0, 0, 0])

print(sched.scheduled_maint_pos, sched.obj_value())

[ 4  6 14  8 12  3 20  9  1 16  5 18 10  2  7 17 13 19 11 15]
[0 0 0 0 0] 473.94773188495776


In [122]:
sched.time_state

array([[ 670.        ,  757.        ,  827.        ,  899.        ,
         989.        , 1441.90199625, 1522.94693322, 1606.63463987,
        1685.03680716, 1768.72451382, 1838.31744883, 1909.67223029,
        1990.71716726, 2047.97717708, 2115.80826563, 2192.44858647,
        2277.89813958, 2336.91999585, 2393.29908244, 2459.36832454,
        1384.64198643],
       [ 902.40660489, 1013.82976538, 1130.35627673, 1218.81435834,
        1313.22634929, 1531.21063633, 1631.57653662, 1741.29858016,
        1858.67564998, 1965.84601809, 2055.15465818, 2155.52055846,
        2261.84036809, 2351.99956665, 2458.31937628, 2573.99532915,
        2659.90173533, 2767.07210344, 2852.12795114, 2965.25222858,
         787.58121049],
       [ 987.02543756, 1080.77345432, 1179.33946376, 1275.14502343,
        1364.65869567, 1581.01020982, 1691.98913396, 1816.40613361,
        1922.35379313, 2026.25861543, 2104.95423166, 2215.9331558 ,
        2332.04960284, 2401.79914014, 2530.16138393, 2631.14238069,


In [26]:
# for i in range(5):
#     sched.scheduled_maint_pos = np.array([3, i])
#     print(sched.scheduled_maint_pos, sched.obj_value())


# MIP 1
sched.scheduled_job_id = np.array([4, 12, 6, 8, 14, 9, 18, 3,
                                   16, 5, 10, 7, 2, 13, 17, 1,
                                   19, 20, 15, 11])
print(sched.scheduled_job_id)
# MIP
sched.scheduled_maint_pos = np.array([1, 1, 4, 0, 6])

print(sched.scheduled_maint_pos, sched.obj_value())

[ 4 12  6  8 14  9 18  3 16  5 10  7  2 13 17  1 19 20 15 11]
[1 1 4 0 6] 1272.4136605808867


In [92]:
# tabu 6
sched.scheduled_job_id = np.array([20, 14, 7, 10, 18, 6, 2, 16, 5, 3, 1, 17, 15, 19, 11, 8, 12, 9, 13, 4])
sched.scheduled_maint_pos = np.array([0, 0, 0, 0, 0])

print(sched.scheduled_maint_pos, sched.obj_value())

[0 0 0 0 0] 0.0


In [77]:
# MIP 6
order = np.array([14,20,7,5,10,18,6,16,2,1,3,17,15,8,19,11,12,9,4,13,])
sched.scheduled_job_id = order
sched.scheduled_maint_pos = np.array([8,2,2,3,0])

print(sched.scheduled_maint_pos, sched.obj_value())


[8 2 2 3 0] 502.52944052357554


In [47]:

sched.Data.REMAIN[1] + sched.Data.MAINT_LEN[1] +\
sched.Data.INIT_PROD_TIME[1, 20]*sched.Data.PROD_DISCOUNT[1] +\
sched.Data.INIT_PROD_TIME[1, 14]*sched.Data.PROD_DISCOUNT[1] +\
sched.Data.INIT_PROD_TIME[1, 7]*sched.Data.PROD_DISCOUNT[1] +\
sched.Data.INIT_PROD_TIME[1, 10]*sched.Data.PROD_DISCOUNT[1] +\
sched.Data.INIT_PROD_TIME[1, 18]*sched.Data.PROD_DISCOUNT[1] +\
sched.Data.INIT_PROD_TIME[1, 6]*sched.Data.PROD_DISCOUNT[1] +\
sched.Data.INIT_PROD_TIME[1, 5]*sched.Data.PROD_DISCOUNT[1] +\
sched.Data.INIT_PROD_TIME[1, 16]*sched.Data.PROD_DISCOUNT[1] +\
sched.Data.INIT_PROD_TIME[1, 3]*sched.Data.PROD_DISCOUNT[1] +\
sched.Data.INIT_PROD_TIME[1, 8]*sched.Data.PROD_DISCOUNT[1] +\
sched.Data.INIT_PROD_TIME[1, 1]*sched.Data.PROD_DISCOUNT[1] 


1902.93395508814

In [78]:
# sched.Data.AFTER_DIS_PROD_TIME
pd.DataFrame(list(sched.Data.DUE_TIME.values()), index=range(1, 21)).reindex(order)

0
14  1720.296236
20  1781.768402
7   2059.615499
5   2179.905060
10  2222.777576
18  2239.106815
6   2231.584547
16  2432.693739
2   2544.693441
1   2603.864494
3   2614.454567
17  2737.338225
15  2756.931062
8   2859.536715
19  2783.520966
11  2918.501056
12  3072.483984
9   3254.414140
4   3295.989534
13  3539.824731

In [88]:
df = pd.DataFrame(np.array(list(sched.Data.AFTER_DIS_PROD_TIME.values())).reshape(5, 20).T, index=range(1, 21))
# df = pd.DataFrame(np.array(list(sched.Data.INIT_PROD_TIME.values())).reshape(5, 20).T, index=range(1, 21))
df.reindex(order)

0          1          2           3          4
14   99.224506  82.990051  60.522420   88.134099  73.669881
20  103.393603  51.657073  61.374848   81.605648  64.355298
7    98.390687  78.755865  79.275846  113.431850  66.895639
5    89.218674  72.828004  76.718561   94.662551  60.968177
10  115.900894  66.900143  60.522420   85.685930  58.427836
18   94.221590  50.810235  66.489419   93.030438  62.661737
6    93.387771  79.602702  62.227277  102.823116  74.516661
16  115.900894  72.828004  60.522420   97.926777  57.581056
2   105.895062  82.990051  69.899133   93.846495  72.823100
1    98.390687  60.125445  65.636991  108.535511  67.742419
3    98.390687  82.143214  51.998135   88.950156  71.976320
17   84.215758  70.287492  75.866132  113.431850  53.347155
15   90.052493  79.602702  63.079705   98.742834  61.814957
8    96.723048  83.836888  73.308847   94.662551  55.887496
19  110.064158  62.665957  59.669992   87.318043  66.048858
11   83.381938  52.503910  51.998135   81.605648  82.137683
12   95.055410  54.197584  56.260278  104.455229  82.984463
9    98.390687  66.900143  62.227277   93.030438  60.968177
4   105.061242  79.602702  55.407849   96.294664  79.597342
13  111.731797  69.440655  52.850564  113.431850  61.814957

In [90]:
sched.Data.PROD_DISCOUNT.values()

dict_values([0.8338193821977671, 0.846837254329738, 0.8524284507036847, 0.8160564760362468, 0.8467802361758076])

In [83]:
pd.DataFrame(sched.time_state.T)

0            1            2            3            4
0    749.000000   886.000000   957.000000  1065.000000  1311.460253
1    873.000000   947.000000  1029.000000  1165.000000  1375.815551
2    991.000000  1186.583950  1455.650179  1594.650179  1661.545818
3   1098.000000  1259.411954  1532.368740  1844.400138  1905.368315
4   1237.000000  1326.312097  1592.891160  1930.086068  1988.513905
5   1350.000000  1400.810235  1659.380579  2023.116507  2085.778244
6   1462.000000  1541.602702  1721.607856  2125.939623  2200.456283
7   1601.000000  1673.828004  1782.130276  2223.866400  2281.447456
8   1876.685974  1959.676025  2029.575158  2317.712895  2390.535995
9   1975.076661  2035.202106  2100.839097  2426.248406  2493.990825
10  2073.467348  2155.610562  2207.608697  2515.198562  2587.174882
11  2157.683106  2227.970598  2303.836730  2628.630412  2681.977567
12  2247.735599  2327.338301  2390.418006  2727.373245  2789.188203
13  2344.458647  2428.295536  2501.604382  2822.035797  2877.923292
14  2454.522806  2517.188763  2576.858754  2909.353840  2975.402698
15  2537.904744  2590.408654  2642.406789  2990.959487  3073.097170
16  2632.960154  2687.157738  2743.418016  3095.414716  3178.399179
17  2731.350841  2798.250984  2860.478261  3188.445154  3249.413331
18  2836.412083  2916.014785  2971.422634  3284.739819  3364.337161
19  2948.143880  3017.584535  3070.435099  3398.171669  3459.986626
20  1770.790912  1107.828086  1376.374333  1749.737587  1237.790373

In [10]:
state = [0]
shift = [0]
for i in range(1, 6):
    if state[i-1] > sched.Data.REMAIN[i]:
        shift.append(state[i-1] - sched.Data.REMAIN[i])
        state.append(state[i-1] + sched.Data.MAINT_LEN[i])
    else:
        shift.append(0)
        state.append(sched.Data.REMAIN[i] + sched.Data.MAINT_LEN[i])
    print(i, state[i], shift[i])

1 799.7909124404941 0
2 960.6189979479333 11.79091244049414
3 1099.2029585384932 97.61899794793328
4 1254.2903666452746 188.20295853849325
5 1384.2526537171145 267.2903666452746


In [86]:
sched.Data.REMAIN
sched.Data.MAINT_LEN.values()

dict_values([169.79091244049417, 160.82808550743917, 138.5839605905599, 155.08740810678145, 129.96228707183982])

In [70]:
sched.Data.N_MACHINE[-1]

5

In [13]:
sched.Data.INIT_PROD_TIME[1,1]

105.0

In [60]:
sched.time_state

array([[ 903.18451583, 1002.40902231, 1100.79970941, 1216.70060354,
        1310.92219373, 1404.30996453, 1493.52863843, 1609.42953255,
        1707.82021965, 1804.54326799, 1902.93395509, 1987.14971269,
        2093.04477423, 2203.10893268, 2286.4908709 , 2376.54336418,
        2471.59877375, 2569.98946085, 2681.72125806, 2786.78250022,
         799.79091244],
       [1012.27607046, 1095.26612139, 1179.55557407, 1283.60074663,
        1361.73242899, 1483.91266644, 1566.3566423 , 1682.25753643,
        1789.96343332, 1888.38015617, 1963.05940015, 2057.4372048 ,
        2176.03482515, 2265.7748895 , 2338.99478067, 2456.14606608,
        2525.79635802, 2636.88960394, 2751.16191292, 2866.38520212,
         960.61899795],
       [1073.65091891, 1155.78854139, 1258.83141998, 1344.12316663,
        1428.22184814, 1546.13994334, 1643.07520286, 1742.77995643,
        1841.96156882, 1961.68900293, 2028.69639085, 2133.30333691,
        2245.93395811, 2325.44488105, 2390.99291616, 2519.22577144,


In [23]:
value = 0
for job_pos, job_id in enumerate(sched.scheduled_job_id):
    value += max(sched.time_state[-1][job_pos] - sched.Data.DUE_TIME[job_id], 0) * sched.Data.WEIGHT[job_id]
    print(job_id, sched.time_state[-1][job_pos] - sched.Data.DUE_TIME[job_id], sched.Data.WEIGHT[job_id])


3 -10.0 100.0
2 30.0 65.0
1 10.0 85.0
4 -120.0 50.0
5 -30.0 32.0


In [125]:
types = ['bestbd', 'runtime', 'mingap', 'obj']
file = '0702U'
for type in types:
    df = pd.concat([pd.read_csv(f'record/model/{file}/{file}_1_30min_{type}.csv'),
                    pd.read_csv(f'record/model/{file}/{file}_6_30min_{type}.csv'),
                    pd.read_csv(f'record/model/{file}/{file}_11_30min_{type}.csv'),
                    pd.read_csv(f'record/model/{file}/{file}_16_30min_{type}.csv'),
                    pd.read_csv(f'record/model/{file}/{file}_21_30min_{type}.csv'),
                    pd.read_csv(f'record/model/{file}/{file}_26_30min_{type}.csv'),
                    pd.read_csv(f'record/model/{file}/{file}_31_30min_{type}.csv')], axis=0, ignore_index=True)
    df.to_csv(f'record/model/{file}_30min_{type}.csv', index=False)
df

benchmark  init_prod_time_L  init_prod_time_H  prod_discount_L  \
0    943.941618       2369.979282       8909.244463      6032.016452   
1   1071.722422       2587.264064        456.862575      5180.089234   
2   4527.968868        669.430318       3969.070639      6842.568331   
3   2391.416812       1377.844226        956.490947      2487.485455   
4   6380.851867       2453.575100       6405.280278      7635.587035   
5    584.062599       4420.492771        546.611478      4950.258223   
6   2923.283216       2491.658019       1198.583312      2284.625154   
7   3885.263835        806.728054       3820.817567      2796.724202   
8   3342.054369       1166.365059      10182.405021       561.504216   
9   2125.157368       2932.840932       4194.763896      1050.105828   
10   970.046933       1956.702235       1862.379073      2321.522561   
11  1091.042970       4028.376894       9661.356908      3470.096134   
12  5859.280909       2553.232865       3936.084597      2762.563899   
13  2212.102363       3089.254665        761.873965      3635.745454   
14  2977.194152       2348.532019        883.953846      5197.277397   
15   919.871805       1662.339927      10040.177539      3979.852877   
16  2299.756279       1873.360005       4551.843627      1273.232438   
17  4687.702824       2004.438893       9921.733405      4530.487631   
18  4094.703250       2263.899165        790.664314      5643.670007   
19  2961.129763       2405.015401       3912.985540      1350.903378   
20  4787.524309       3318.587665       5551.297906      3948.602181   
21  2604.602939       3118.429299       5637.045624      3285.698414   
22   715.643354       2968.199825        494.794035      3280.645081   
23   524.432066       3232.857963       8097.777515      3683.762650   
24  1953.126817       2377.723665       1642.797946      1655.525577   
25  1083.306642       1959.444072       2065.287247      6371.027377   
26  3073.657787       2426.673871      10267.789113      1607.859119   
27   674.955789        900.159474       1445.194935      2144.734873   
28  2398.595396        697.767549       4725.654449      1695.824538   
29  1794.112588       2227.790141       2013.672366      2019.551873   
30  2690.378270       1539.905876       2815.927114      3947.351328   
31  4874.784690       4082.159620       6452.663533      1723.243828   
32  4043.997580        822.979140       1719.353290       498.230844   
33  2862.071525       1281.475158       1698.260250      1594.811969   
34  2666.172657       1085.020234       7945.111485      4338.351208   

    prod_discount_H     weight_L     weight_H    due_time_L   due_time_H  \
0       1424.761610  1662.687287  4533.978628   9368.682783  1215.352709   
1        209.001358  2637.616706  1148.401796   9520.748178  4399.409625   
2       3002.906967  1319.100694  4263.023215   8502.271885  2212.643689   
3       7934.612180  1255.734890  6765.240787  10873.215806   377.955668   
4       3843.537345  4301.469449  4029.391444  14443.338697  1085.932286   
5       1956.355652  4514.468257  1046.733156   8563.736575   446.917028   
6       4336.266810  2327.235586  2880.493504   9392.067682  5262.000207   
7       1889.314089  1442.659067  3273.189999  12605.282539   504.742963   
8       2071.676138  1733.942923   657.791748  10165.424655  1819.735230   
9       2555.701690  2669.424519  7292.418010  10944.121273   600.323375   
10      1379.671535  1438.606491  3099.665708  10128.253193   803.589115   
11      2410.673672   777.274923  6438.377788  10904.041188  1381.433672   
12      1151.171419  3187.697826  3080.718218   7869.917809   957.853449   
13      1794.901393  3470.569890   679.157445  10230.423826  4044.917515   
14     10476.028753  6331.813676  2134.622730   6594.081108  1020.305346   
15      2255.383590  2134.527787  2201.547806   6456.719142   106.758647   
16      5623.504578  3400.301863   749.144821  10854.509768  4035.813396   
17      1149.156797  2340.258765  1833.742998

In [106]:
pd.read_csv('record/model/0627/0627_1_30min_bestbd.csv')

benchmark  init_prod_time_L  init_prod_time_H  prod_discount_L  \
0   940.253136       1552.620220       3340.179856      2636.210438   
1  1071.722422       1654.514551        456.862575      2570.306888   
2  1901.702626        669.430318       1203.099703      2583.469786   
3  1625.557723       1368.169317        952.805747      2487.485454   
4  2204.433307       2019.971419       1366.329382      2591.040291   

   prod_discount_H     weight_L     weight_H   due_time_L   due_time_H  \
0      1415.664404  1278.678948  2864.447485  2948.720652  1210.676308   
1       209.001358  1144.958075  1148.401796  2957.609787  2776.129849   
2      3002.906967  1319.100694  2350.616866  2486.732402  2212.643689   
3      3463.799518  1255.734890  3346.605964  1671.343286   377.955668   
4      2590.450412  2508.146080  2791.335166  4122.811589  1085.932286   

   maint_len_L  maint_len_H  
0   880.932480   627.850026  
1  2264.623842  1312.111438  
2  1590.930423  1442.021972  
3   646.655573   613.513829  
4  1727.039124   844.281000

In [109]:
df.to_csv('record/model/0627_30min_bestbd.csv', index=False)